from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from config import ConfigError, settings
from lead_utils import ensure_contact_and_maps

logger = logging.getLogger(__name__)

Lead = dict[str, Any]


def is_supabase_configured() -> bool:
    return bool(settings.supabase_database_url)


def _connect() -> Any:
    if not is_supabase_configured():
        raise ConfigError("Supabase belum dikonfigurasi. Isi SUPABASE_DATABASE_URL di .env.")
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:
        raise RuntimeError("Dependency psycopg belum terpasang. Jalankan: pip install -r requirements.txt") from exc
    return psycopg.connect(settings.supabase_database_url, row_factory=dict_row)


def init_db() -> None:
    if not is_supabase_configured():
        logger.warning("Supabase belum dikonfigurasi; dashboard akan tampil tanpa data.")
        return
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                create table if not exists public.leads (
                  id bigint generated by default as identity primary key,
                  tanggal date not null,
                  nama_bisnis text not null,
                  kategori text not null,
                  kota text not null,
                  kontak text,
                  kontak_bisa_dihubungi text,
                  email text,
                  instagram text,
                  website text,
                  google_maps_link text,
                  status_website text,
                  sumber text,
                  skor_peluang integer,
                  status text default 'draft',
                  catatan text,
                  created_at timestamptz not null default now(),
                  constraint leads_unique_business_city unique (nama_bisnis, kota)
                )
                """
            )
            cur.execute("create index if not exists leads_tanggal_idx on public.leads (tanggal desc)")
            cur.execute("create index if not exists leads_status_idx on public.leads (status)")
            cur.execute("create index if not exists leads_status_website_idx on public.leads (status_website)")
        conn.commit()
    logger.info("Supabase Postgres siap.")


def lead_exists(nama_bisnis: str, kota: str) -> bool:
    if not is_supabase_configured():
        return False
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                select id
                from public.leads
                where lower(nama_bisnis) = lower(%s)
                  and lower(kota) = lower(%s)
                limit 1
                """,
                (nama_bisnis, kota),
            )
            return cur.fetchone() is not None


def save_lead(lead: Lead) -> int | None:
    if not is_supabase_configured():
        raise ConfigError("Supabase belum dikonfigurasi. Isi SUPABASE_DATABASE_URL di .env.")

    lead = ensure_contact_and_maps(lead)
    payload = {
        "tanggal": lead.get("tanggal") or datetime.now().date().isoformat(),
        "nama_bisnis": lead.get("nama_bisnis", ""),
        "kategori": lead.get("kategori", ""),
        "kota": lead.get("kota", ""),
        "kontak": lead.get("kontak", ""),
        "kontak_bisa_dihubungi": lead.get("kontak_bisa_dihubungi", ""),
        "email": lead.get("email", ""),
        "instagram": lead.get("instagram", ""),
        "website": lead.get("website", ""),
        "google_maps_link": lead.get("google_maps_link", ""),
        "status_website": lead.get("status_website", ""),
        "sumber": lead.get("sumber", ""),
        "skor_peluang": int(lead.get("skor_peluang", 1)),
        "status": lead.get("status") or "draft",
        "catatan": lead.get("catatan", ""),
    }

    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                insert into public.leads (
                    tanggal, nama_bisnis, kategori, kota, kontak, kontak_bisa_dihubungi,
                    email, instagram, website, google_maps_link, status_website, sumber,
                    skor_peluang, status, catatan
                )
                values (
                    %(tanggal)s, %(nama_bisnis)s, %(kategori)s, %(kota)s, %(kontak)s,
                    %(kontak_bisa_dihubungi)s, %(email)s, %(instagram)s, %(website)s,
                    %(google_maps_link)s, %(status_website)s, %(sumber)s, %(skor_peluang)s,
                    %(status)s, %(catatan)s
                )
                on conflict (nama_bisnis, kota) do nothing
                returning id
                """,
                payload,
            )
            row = cur.fetchone()
        conn.commit()

    if not row:
        logger.info("Lead duplikat dilewati: %s (%s)", payload["nama_bisnis"], payload["kota"])
        return None
    return int(row["id"])


def get_today_leads() -> list[Lead]:
    if not is_supabase_configured():
        return []
    today = datetime.now().date().isoformat()
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute("select * from public.leads where tanggal = %s order by id desc", (today,))
            return list(cur.fetchall())


def get_latest_leads(limit: int = 5) -> list[Lead]:
    if not is_supabase_configured():
        return []
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute("select * from public.leads order by id desc limit %s", (limit,))
            return list(cur.fetchall())


def get_all_leads() -> list[Lead]:
    if not is_supabase_configured():
        return []
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute("select * from public.leads order by id desc")
            return list(cur.fetchall())


def get_lead_by_id(id: int) -> Lead | None:
    if not is_supabase_configured():
        return None
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute("select * from public.leads where id = %s limit 1", (id,))
            row = cur.fetchone()
            return dict(row) if row else None


def update_status(id: int, status: str) -> bool:
    allowed = {"draft", "approved", "skipped", "contacted", "closed"}
    if status not in allowed:
        raise ValueError(f"Status tidak valid: {status}")
    if not is_supabase_configured():
        raise ConfigError("Supabase belum dikonfigurasi. Isi SUPABASE_DATABASE_URL di .env.")

    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "update public.leads set status = %s where id = %s returning id",
                (status, id),
            )
            row = cur.fetchone()
        conn.commit()
    return row is not None


def count_today() -> int:
    return len(get_today_leads())


def get_dashboard_stats() -> dict[str, int]:
    leads = get_all_leads()
    return {
        "total": len(leads),
        "draft": sum(1 for lead in leads if lead.get("status") == "draft"),
        "approved": sum(1 for lead in leads if lead.get("status") == "approved"),
        "no_website": sum(1 for lead in leads if lead.get("status_website") == "Belum ada"),
        "social_only": sum(1 for lead in leads if lead.get("status_website") == "Hanya sosial media"),
        "today": count_today(),
    }
