create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  tanggal date not null,
  nama_bisnis text not null,
  kategori text not null,
  kota text not null,
  kontak text,
  kontak_bisa_dihubungi text,
  email text,
  instagram text,
  website text,
  google_maps_link text,
  status_website text,
  sumber text,
  skor_peluang integer,
  status text default 'draft',
  catatan text,
  created_at timestamptz not null default now(),
  constraint leads_unique_business_city unique (nama_bisnis, kota)
);

create index if not exists leads_tanggal_idx on public.leads (tanggal desc);
create index if not exists leads_status_idx on public.leads (status);
create index if not exists leads_status_website_idx on public.leads (status_website);

